### ISSUE TITLE
Color change request on mixplorer

### ISSUE THREAD

**Issue by jeyjai** [dracula/mixplorer#12]
I really like your themes and use several of them, but i have a question about the one for mixplorer and it's regarding the tiny black text used for some files, like resolution on images or a preview on text files, right below the file name.

Could you possibly change this to a slightly more visible color, don't really care which color, just want it a bit more visible. 

Or if you know of a way i can change it myself on a android system.

![20240625_230313](https://github.com/dracula/mixplorer/assets/7854537/bf8a9a9f-cce5-4b01-8947-3a5c14788250)

**Comment by Dhyfer1** [comment]
> Or if you know of a way i can change it myself on a android system.

It's easy, I'll tell you how to do it:

- Click on the dracula-purple.mit theme file and in the "Open with" window select Explore 
- Now click on the properties.xml file and in the "Open with" window select Code Editor or Text Editor, either of the two works
- When you have the properties.xml file open, go to line 38 "text grid secondary" and edit the hex value that appears with a new value, after the # sign
- When you're done editing the value, save your changes. To do this, click on the floppy disk icon located in the upper right corner and close the properties.xml file with the arrow in the upper left corner
- Now go to the location of the dracula-purple.mit theme file, click on it and select Import, the new color is now displayed.

You're welcome.

**Comment by Dhyfer1** [comment]
> Or if you know of a way i can change it myself on a android system.

It's easy, just follow the steps in the image. 

![My_Awesome_App_Diagram_ScreenshotFlow.png](https://github.com/dracula/mixplorer/assets/50301201/ef7c01c6-b687-4953-8c6b-a3dca1129170)

When you open the properties.xml file add this entry anywhere:

```xml
<entry key="text_grid_tertiary">#FAC21D</entry>
```

As you can see, I added it on line 39. #FAC21D it's a custom color, you can change it to any other color. When you finish doing all the steps, just import the theme and you will be able to see your color

**Comment by jeyjai** [comment]
Thank you so much

**Comment by Dhyfer1** [comment]
You're welcome 🤗

**Comment by Dhyfer1** [comment]
@jeyjai Forgot something, when you select an element, for example an image, the text turns black again. If you also want to use a custom color for a selected element, you must add this entry to the properties.xml file:

```xml
<entry key="text_grid_tertiary_inverse">#FAC21D</entry>
```

As I said before, #FAC21D is a custom color, you can change this value to any color. Just follow the same process that I showed you in the image and at the end you import the theme.

**Comment by jeyjai** [comment]
Thnx, didnt even notice that at first.
Tried a few colors but went with the same color as `text_grid_secondary` to have them match
