### ISSUE TITLE
Incorrect color of the revisit text

### ISSUE THREAD

**Issue by Pushkin31** [dracula/mixplorer#13]
Recently mix updated and something went wrong that now the text on the "Dracula" theme behaves like this (black text). Could you please fix this? Thanks!!!

<details>
  <summary>screen</summary>

![IMG_20240707_233426.jpg](https://github.com/dracula/mixplorer/assets/35974828/e98423f7-a2da-4770-9522-bdaf3b6c11b7)

</details>

**Comment by Dhyfer1** [comment]
Too easy, just follow the steps in my [comment](https://github.com/dracula/mixplorer/issues/12#issuecomment-2192920682)

**Comment by sionta** [comment]
New release [v1.3.1](https://github.com/dracula/mixplorer/releases/tag/v1.3.1) Thanks @Dhyfer1
