### ISSUE TITLE
Icons in the panel without a background

### ISSUE THREAD

**Issue by Pushkin31** [dracula/mixplorer#4]
Hello. Can you please tell me why the icons have a background - should it be so?
I would like them to be transparent, as in the screenshots in README

<details>
<summary>As now</summary>

![Screenshot_2021_10_25_16_09_04_90_07f20907771ad09ffa2dcbecf65bb740](https://user-images.githubusercontent.com/35974828/138701571-959675d2-0224-4c28-b811-c1d7c6bd7234.jpg)

</details>

<details>
<summary>As it should be</summary>

![brave_HSIAZ7N5Rh](https://user-images.githubusercontent.com/35974828/138701432-cf6730e6-ade4-419f-afcc-5a3e561f2196.png)

</details>

**Comment by Pushkin31** [comment]
when selecting text in the code editor - the selected text is not visible because of the color of the selection
the same when selecting other text - it is badly visible.
I propose to weaken the transparency of the selection, as well as to change the color

<details>
<summary>Screenshot</summary>

![Screenshot_2021_11_10_18_31_13_92_07f20907771ad09ffa2dcbecf65bb740](https://user-images.githubusercontent.com/35974828/141792303-f1310286-d07d-44fe-88ea-32c6da068842.jpg)


</details>

**Comment by kybo15** [comment]
@Pushkin31 I will fix it soon. and thanks for being a tester for me, if it is really fixed i will let you know as soon as possible.

- [ ] text_edit_selection_background: https://github.com/dracula/mixplorer/issues/4#issuecomment-968925140
- [ ] notification_server: https://github.com/dracula/mixplorer/issues/4#issuecomment-952234665

**Comment by Pushkin31** [comment]
health. Have you thought about fixing the bugs?)

**Comment by kybo15** [comment]
Hy @Pushkin31 , I have fixed it just a few obstacles on my PC so I will immediately push later.

**Comment by Pushkin31** [comment]
@kybo15 I decided to figure it out myself and realized that I just need to delete the file "notification_server.png", so that mix uses its own icon :)
