### ISSUE TITLE
Requires monocolor icons

### ISSUE THREAD

**Issue by 4nd123** [dracula/mixplorer#9]
I have a suggestion and request please provide mono or dualtone icons and I suggest using [**tabler-icons**](https://github.com/tabler/tabler-icons). 🤩

<details><summary>Example</summary>
<p>

![Screenshot_2023-06-26-23-38-02-952_com mixplorer](https://github.com/dracula/mixplorer/assets/99480885/be17c604-c536-4e5b-92eb-3c1b04b2efe3)

![Screenshot_2023-06-26-23-37-43-696_com mixplorer](https://github.com/dracula/mixplorer/assets/99480885/372d9f78-839e-4a6a-a95b-8e97178ee785)

</p>
</details>

**Comment by sionta** [comment]
https://github.com/dracula/mixplorer/releases/tag/v1.3.0
